'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace iLibraryService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineOnline", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum MachineOnline As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Offline = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Online = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineOnlineStateResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MachineOnlineStateResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineProcessingState", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum MachineProcessingState As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Initial = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Idle = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Setup = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ready = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Execute = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Pause = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LotSetUp = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Maintenance = 7
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateMachineStateResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateMachineStateResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SetupLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SetupLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As iLibraryService.SetupLotResult.Status
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecipeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As iLibraryService.SetupLotResult.Status
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Recipe() As String
            Get
                Return Me.RecipeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RecipeField, value) <> true) Then
                    Me.RecipeField = value
                    Me.RaisePropertyChanged("Recipe")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="SetupLotResult.Status", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
        Public Enum Status As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Pass = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            NotPass = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Warning = 2
        End Enum
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StartLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class StartLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Judge", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum Judge As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NG = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OK = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateFirstinspectionResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateFirstinspectionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EndLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EndLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateFinalinspectionResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateFinalinspectionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AlarmState", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum AlarmState As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RESET = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [SET] = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineAlarmResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MachineAlarmResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CancelLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CancelLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReinputResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReinputResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="iLibraryService.IServiceiLibrary")>  _
    Public Interface IServiceiLibrary
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/MachineOnlineState", ReplyAction:="http://tempuri.org/IServiceiLibrary/MachineOnlineStateResponse")>  _
        Function MachineOnlineState(ByVal mcNo As String, ByVal online As iLibraryService.MachineOnline) As iLibraryService.MachineOnlineStateResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/UpdateMachineState", ReplyAction:="http://tempuri.org/IServiceiLibrary/UpdateMachineStateResponse")>  _
        Function UpdateMachineState(ByVal mcNo As String, ByVal state As iLibraryService.MachineProcessingState) As iLibraryService.UpdateMachineStateResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/SetupLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/SetupLotResponse")>  _
        Function SetupLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String) As iLibraryService.SetupLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/StartLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/StartLotResponse")>  _
        Function StartLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal recipe As String) As iLibraryService.StartLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/UpdateFirstinspection", ReplyAction:="http://tempuri.org/IServiceiLibrary/UpdateFirstinspectionResponse")>  _
        Function UpdateFirstinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFirstinspectionResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/EndLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/EndLotResponse")>  _
        Function EndLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.EndLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/UpdateFinalinspection", ReplyAction:="http://tempuri.org/IServiceiLibrary/UpdateFinalinspectionResponse")>  _
        Function UpdateFinalinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFinalinspectionResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/MachineAlarm", ReplyAction:="http://tempuri.org/IServiceiLibrary/MachineAlarmResponse")>  _
        Function MachineAlarm(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal AlarmNo As String, ByVal alarm As iLibraryService.AlarmState) As iLibraryService.MachineAlarmResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/CancelLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/CancelLotResponse")>  _
        Function CancelLot(ByVal mcNo As String, ByVal lotNo As String, ByVal opNo As String) As iLibraryService.CancelLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/Reinput", ReplyAction:="http://tempuri.org/IServiceiLibrary/ReinputResponse")>  _
        Function Reinput(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.ReinputResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/ReinputAndHoldLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/ReinputAndHoldLotResponse")>  _
        Function ReinputAndHoldLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.ReinputResult
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceiLibraryChannel
        Inherits iLibraryService.IServiceiLibrary, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceiLibraryClient
        Inherits System.ServiceModel.ClientBase(Of iLibraryService.IServiceiLibrary)
        Implements iLibraryService.IServiceiLibrary
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function MachineOnlineState(ByVal mcNo As String, ByVal online As iLibraryService.MachineOnline) As iLibraryService.MachineOnlineStateResult Implements iLibraryService.IServiceiLibrary.MachineOnlineState
            Return MyBase.Channel.MachineOnlineState(mcNo, online)
        End Function
        
        Public Function UpdateMachineState(ByVal mcNo As String, ByVal state As iLibraryService.MachineProcessingState) As iLibraryService.UpdateMachineStateResult Implements iLibraryService.IServiceiLibrary.UpdateMachineState
            Return MyBase.Channel.UpdateMachineState(mcNo, state)
        End Function
        
        Public Function SetupLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String) As iLibraryService.SetupLotResult Implements iLibraryService.IServiceiLibrary.SetupLot
            Return MyBase.Channel.SetupLot(lotNo, mcNo, opNo, processName, layerNo)
        End Function
        
        Public Function StartLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal recipe As String) As iLibraryService.StartLotResult Implements iLibraryService.IServiceiLibrary.StartLot
            Return MyBase.Channel.StartLot(lotNo, mcNo, opNo, recipe)
        End Function
        
        Public Function UpdateFirstinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFirstinspectionResult Implements iLibraryService.IServiceiLibrary.UpdateFirstinspection
            Return MyBase.Channel.UpdateFirstinspection(lotNo, opNo, judge, mcNo)
        End Function
        
        Public Function EndLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.EndLotResult Implements iLibraryService.IServiceiLibrary.EndLot
            Return MyBase.Channel.EndLot(lotNo, mcNo, opNo, good, ng)
        End Function
        
        Public Function UpdateFinalinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFinalinspectionResult Implements iLibraryService.IServiceiLibrary.UpdateFinalinspection
            Return MyBase.Channel.UpdateFinalinspection(lotNo, opNo, judge, mcNo)
        End Function
        
        Public Function MachineAlarm(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal AlarmNo As String, ByVal alarm As iLibraryService.AlarmState) As iLibraryService.MachineAlarmResult Implements iLibraryService.IServiceiLibrary.MachineAlarm
            Return MyBase.Channel.MachineAlarm(lotNo, mcNo, opNo, AlarmNo, alarm)
        End Function
        
        Public Function CancelLot(ByVal mcNo As String, ByVal lotNo As String, ByVal opNo As String) As iLibraryService.CancelLotResult Implements iLibraryService.IServiceiLibrary.CancelLot
            Return MyBase.Channel.CancelLot(mcNo, lotNo, opNo)
        End Function
        
        Public Function Reinput(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.ReinputResult Implements iLibraryService.IServiceiLibrary.Reinput
            Return MyBase.Channel.Reinput(lotNo, mcNo, opNo, good, ng)
        End Function
        
        Public Function ReinputAndHoldLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.ReinputResult Implements iLibraryService.IServiceiLibrary.ReinputAndHoldLot
            Return MyBase.Channel.ReinputAndHoldLot(lotNo, mcNo, opNo, good, ng)
        End Function
    End Class
End Namespace
