'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace iLibraryService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineOnline", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum MachineOnline As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Offline = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Online = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineOnlineStateResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MachineOnlineStateResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MessageType", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum MessageType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Apcs = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ApcsPro = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unknown = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineProcessingState", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum MachineProcessingState As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Initial = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Idle = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Setup = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Ready = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Execute = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Pause = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        LotSetUp = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Maintenance = 7
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateMachineStateResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateMachineStateResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SetupLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SetupLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorNoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As iLibraryService.SetupLotResult.Status
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RecipeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorNo() As String
            Get
                Return Me.ErrorNoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorNoField, value) <> true) Then
                    Me.ErrorNoField = value
                    Me.RaisePropertyChanged("ErrorNo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As iLibraryService.SetupLotResult.Status
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Recipe() As String
            Get
                Return Me.RecipeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RecipeField, value) <> true) Then
                    Me.RecipeField = value
                    Me.RaisePropertyChanged("Recipe")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
        
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
         System.Runtime.Serialization.DataContractAttribute(Name:="SetupLotResult.Status", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
        Public Enum Status As Integer
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Pass = 0
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            NotPass = 1
            
            <System.Runtime.Serialization.EnumMemberAttribute()>  _
            Warning = 2
        End Enum
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RunMode", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum RunMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Normal = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Separated = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SeparatedEnd = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ReRun = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StartLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class StartLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OnlineStartResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OnlineStartResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OnlineEndResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OnlineEndResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Judge", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum Judge As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NG = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OK = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateFirstinspectionResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateFirstinspectionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EndLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EndLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UpdateFinalinspectionResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UpdateFinalinspectionResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AlarmState", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum AlarmState As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RESET = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [SET] = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MachineAlarmResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MachineAlarmResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CancelLotResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CancelLotResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EndMode", [Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum EndMode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Normal = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AbnormalEndReset = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AbnormalEndAccumulate = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReinputResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReinputResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CheckLotApcsProResult", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CheckLotApcsProResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CauseField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FunctionNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsPassField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubFunctionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As iLibraryService.MessageType
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cause() As String
            Get
                Return Me.CauseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CauseField, value) <> true) Then
                    Me.CauseField = value
                    Me.RaisePropertyChanged("Cause")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FunctionName() As String
            Get
                Return Me.FunctionNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FunctionNameField, value) <> true) Then
                    Me.FunctionNameField = value
                    Me.RaisePropertyChanged("FunctionName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPass() As Boolean
            Get
                Return Me.IsPassField
            End Get
            Set
                If (Me.IsPassField.Equals(value) <> true) Then
                    Me.IsPassField = value
                    Me.RaisePropertyChanged("IsPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubFunction() As String
            Get
                Return Me.SubFunctionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubFunctionField, value) <> true) Then
                    Me.SubFunctionField = value
                    Me.RaisePropertyChanged("SubFunction")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Type() As iLibraryService.MessageType
            Get
                Return Me.TypeField
            End Get
            Set
                If (Me.TypeField.Equals(value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="iLibraryService.IServiceiLibrary")>  _
    Public Interface IServiceiLibrary
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/MachineOnlineState", ReplyAction:="http://tempuri.org/IServiceiLibrary/MachineOnlineStateResponse")>  _
        Function MachineOnlineState(ByVal mcNo As String, ByVal online As iLibraryService.MachineOnline) As iLibraryService.MachineOnlineStateResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/UpdateMachineState", ReplyAction:="http://tempuri.org/IServiceiLibrary/UpdateMachineStateResponse")>  _
        Function UpdateMachineState(ByVal mcNo As String, ByVal state As iLibraryService.MachineProcessingState) As iLibraryService.UpdateMachineStateResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/SetupLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/SetupLotResponse")>  _
        Function SetupLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String) As iLibraryService.SetupLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/SetupLotNoCheckLicenser", ReplyAction:="http://tempuri.org/IServiceiLibrary/SetupLotNoCheckLicenserResponse")>  _
        Function SetupLotNoCheckLicenser(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String) As iLibraryService.SetupLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/SetupLotCustomMode", ReplyAction:="http://tempuri.org/IServiceiLibrary/SetupLotCustomModeResponse")>  _
        Function SetupLotCustomMode(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String, ByVal runMode As iLibraryService.RunMode) As iLibraryService.SetupLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/SetupLotCustomModeNoCheckLicenser", ReplyAction:="http://tempuri.org/IServiceiLibrary/SetupLotCustomModeNoCheckLicenserResponse")>  _
        Function SetupLotCustomModeNoCheckLicenser(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String, ByVal runMode As iLibraryService.RunMode) As iLibraryService.SetupLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/StartLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/StartLotResponse")>  _
        Function StartLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal recipe As String) As iLibraryService.StartLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/StartLotCustomMode", ReplyAction:="http://tempuri.org/IServiceiLibrary/StartLotCustomModeResponse")>  _
        Function StartLotCustomMode(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal recipe As String, ByVal runMode As iLibraryService.RunMode) As iLibraryService.StartLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/OnlineStart", ReplyAction:="http://tempuri.org/IServiceiLibrary/OnlineStartResponse")>  _
        Function OnlineStart(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String) As iLibraryService.OnlineStartResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/OnlineEnd", ReplyAction:="http://tempuri.org/IServiceiLibrary/OnlineEndResponse")>  _
        Function OnlineEnd(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.OnlineEndResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/UpdateFirstinspection", ReplyAction:="http://tempuri.org/IServiceiLibrary/UpdateFirstinspectionResponse")>  _
        Function UpdateFirstinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFirstinspectionResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/EndLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/EndLotResponse")>  _
        Function EndLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.EndLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/EndLotNoCheckLicenser", ReplyAction:="http://tempuri.org/IServiceiLibrary/EndLotNoCheckLicenserResponse")>  _
        Function EndLotNoCheckLicenser(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.EndLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/UpdateFinalinspection", ReplyAction:="http://tempuri.org/IServiceiLibrary/UpdateFinalinspectionResponse")>  _
        Function UpdateFinalinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFinalinspectionResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/MachineAlarm", ReplyAction:="http://tempuri.org/IServiceiLibrary/MachineAlarmResponse")>  _
        Function MachineAlarm(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal AlarmNo As String, ByVal alarm As iLibraryService.AlarmState) As iLibraryService.MachineAlarmResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/CancelLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/CancelLotResponse")>  _
        Function CancelLot(ByVal mcNo As String, ByVal lotNo As String, ByVal opNo As String) As iLibraryService.CancelLotResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/Reinput", ReplyAction:="http://tempuri.org/IServiceiLibrary/ReinputResponse")>  _
        Function Reinput(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer, ByVal endMode As iLibraryService.EndMode) As iLibraryService.ReinputResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/ReinputAndHoldLot", ReplyAction:="http://tempuri.org/IServiceiLibrary/ReinputAndHoldLotResponse")>  _
        Function ReinputAndHoldLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer, ByVal endMode As iLibraryService.EndMode) As iLibraryService.ReinputResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceiLibrary/CheckLotApcsProManual", ReplyAction:="http://tempuri.org/IServiceiLibrary/CheckLotApcsProManualResponse")>  _
        Function CheckLotApcsProManual(ByVal lotNo As String, ByVal mcNo As String, ByVal package As String) As iLibraryService.CheckLotApcsProResult
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IServiceiLibraryChannel
        Inherits iLibraryService.IServiceiLibrary, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceiLibraryClient
        Inherits System.ServiceModel.ClientBase(Of iLibraryService.IServiceiLibrary)
        Implements iLibraryService.IServiceiLibrary
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function MachineOnlineState(ByVal mcNo As String, ByVal online As iLibraryService.MachineOnline) As iLibraryService.MachineOnlineStateResult Implements iLibraryService.IServiceiLibrary.MachineOnlineState
            Return MyBase.Channel.MachineOnlineState(mcNo, online)
        End Function
        
        Public Function UpdateMachineState(ByVal mcNo As String, ByVal state As iLibraryService.MachineProcessingState) As iLibraryService.UpdateMachineStateResult Implements iLibraryService.IServiceiLibrary.UpdateMachineState
            Return MyBase.Channel.UpdateMachineState(mcNo, state)
        End Function
        
        Public Function SetupLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String) As iLibraryService.SetupLotResult Implements iLibraryService.IServiceiLibrary.SetupLot
            Return MyBase.Channel.SetupLot(lotNo, mcNo, opNo, processName, layerNo)
        End Function
        
        Public Function SetupLotNoCheckLicenser(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String) As iLibraryService.SetupLotResult Implements iLibraryService.IServiceiLibrary.SetupLotNoCheckLicenser
            Return MyBase.Channel.SetupLotNoCheckLicenser(lotNo, mcNo, opNo, processName, layerNo)
        End Function
        
        Public Function SetupLotCustomMode(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String, ByVal runMode As iLibraryService.RunMode) As iLibraryService.SetupLotResult Implements iLibraryService.IServiceiLibrary.SetupLotCustomMode
            Return MyBase.Channel.SetupLotCustomMode(lotNo, mcNo, opNo, processName, layerNo, runMode)
        End Function
        
        Public Function SetupLotCustomModeNoCheckLicenser(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal processName As String, ByVal layerNo As String, ByVal runMode As iLibraryService.RunMode) As iLibraryService.SetupLotResult Implements iLibraryService.IServiceiLibrary.SetupLotCustomModeNoCheckLicenser
            Return MyBase.Channel.SetupLotCustomModeNoCheckLicenser(lotNo, mcNo, opNo, processName, layerNo, runMode)
        End Function
        
        Public Function StartLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal recipe As String) As iLibraryService.StartLotResult Implements iLibraryService.IServiceiLibrary.StartLot
            Return MyBase.Channel.StartLot(lotNo, mcNo, opNo, recipe)
        End Function
        
        Public Function StartLotCustomMode(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal recipe As String, ByVal runMode As iLibraryService.RunMode) As iLibraryService.StartLotResult Implements iLibraryService.IServiceiLibrary.StartLotCustomMode
            Return MyBase.Channel.StartLotCustomMode(lotNo, mcNo, opNo, recipe, runMode)
        End Function
        
        Public Function OnlineStart(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String) As iLibraryService.OnlineStartResult Implements iLibraryService.IServiceiLibrary.OnlineStart
            Return MyBase.Channel.OnlineStart(lotNo, mcNo, opNo)
        End Function
        
        Public Function OnlineEnd(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.OnlineEndResult Implements iLibraryService.IServiceiLibrary.OnlineEnd
            Return MyBase.Channel.OnlineEnd(lotNo, mcNo, opNo, good, ng)
        End Function
        
        Public Function UpdateFirstinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFirstinspectionResult Implements iLibraryService.IServiceiLibrary.UpdateFirstinspection
            Return MyBase.Channel.UpdateFirstinspection(lotNo, opNo, judge, mcNo)
        End Function
        
        Public Function EndLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.EndLotResult Implements iLibraryService.IServiceiLibrary.EndLot
            Return MyBase.Channel.EndLot(lotNo, mcNo, opNo, good, ng)
        End Function
        
        Public Function EndLotNoCheckLicenser(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer) As iLibraryService.EndLotResult Implements iLibraryService.IServiceiLibrary.EndLotNoCheckLicenser
            Return MyBase.Channel.EndLotNoCheckLicenser(lotNo, mcNo, opNo, good, ng)
        End Function
        
        Public Function UpdateFinalinspection(ByVal lotNo As String, ByVal opNo As String, ByVal judge As iLibraryService.Judge, ByVal mcNo As String) As iLibraryService.UpdateFinalinspectionResult Implements iLibraryService.IServiceiLibrary.UpdateFinalinspection
            Return MyBase.Channel.UpdateFinalinspection(lotNo, opNo, judge, mcNo)
        End Function
        
        Public Function MachineAlarm(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal AlarmNo As String, ByVal alarm As iLibraryService.AlarmState) As iLibraryService.MachineAlarmResult Implements iLibraryService.IServiceiLibrary.MachineAlarm
            Return MyBase.Channel.MachineAlarm(lotNo, mcNo, opNo, AlarmNo, alarm)
        End Function
        
        Public Function CancelLot(ByVal mcNo As String, ByVal lotNo As String, ByVal opNo As String) As iLibraryService.CancelLotResult Implements iLibraryService.IServiceiLibrary.CancelLot
            Return MyBase.Channel.CancelLot(mcNo, lotNo, opNo)
        End Function
        
        Public Function Reinput(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer, ByVal endMode As iLibraryService.EndMode) As iLibraryService.ReinputResult Implements iLibraryService.IServiceiLibrary.Reinput
            Return MyBase.Channel.Reinput(lotNo, mcNo, opNo, good, ng, endMode)
        End Function
        
        Public Function ReinputAndHoldLot(ByVal lotNo As String, ByVal mcNo As String, ByVal opNo As String, ByVal good As Integer, ByVal ng As Integer, ByVal endMode As iLibraryService.EndMode) As iLibraryService.ReinputResult Implements iLibraryService.IServiceiLibrary.ReinputAndHoldLot
            Return MyBase.Channel.ReinputAndHoldLot(lotNo, mcNo, opNo, good, ng, endMode)
        End Function
        
        Public Function CheckLotApcsProManual(ByVal lotNo As String, ByVal mcNo As String, ByVal package As String) As iLibraryService.CheckLotApcsProResult Implements iLibraryService.IServiceiLibrary.CheckLotApcsProManual
            Return MyBase.Channel.CheckLotApcsProManual(lotNo, mcNo, package)
        End Function
    End Class
End Namespace
